ERROR - 2024-12-07 17:38:24 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'u679963801_bmynew'@'localhost' (using password: YES) in C:\xampp\htdocs\abcbmy\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\abcbmy\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', 'u679963801_bmyn...', Object(SensitiveParameterValue), 'u679963801_bmyn...', 3306, '', 0)
#1 C:\xampp\htdocs\abcbmy\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\abcbmy\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\abcbmy\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\abcbmy\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\abcbmy\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\abcbmy\app\Controllers\Yacht.php(22): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(941): App\Controllers\Yacht->index()
#8 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Yacht))
#9 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\abcbmy\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\abcbmy\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\abcbmy\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\abcbmy\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\abcbmy\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\abcbmy\system\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\abcbmy\system\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\abcbmy\app\Controllers\Yacht.php(22): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(941): App\Controllers\Yacht->index()
#7 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Yacht))
#8 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\abcbmy\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2024-12-07 17:38:24 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `yacht`', [], false)
 3 SYSTEMPATH\Model.php(242): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(638): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Yacht.php(22): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(941): App\Controllers\Yacht->index()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Yacht))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-12-07 17:39:49 --> CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "https//localhost/abcbmy/" is not a valid URL.
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 SYSTEMPATH\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
 2 SYSTEMPATH\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), null, null)
 3 SYSTEMPATH\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', null)
 4 SYSTEMPATH\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
 5 SYSTEMPATH\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
 6 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(null, false)
 7 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', [...])
 8 SYSTEMPATH\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', null)
 9 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
10 SYSTEMPATH\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', [])
11 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
12 SYSTEMPATH\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
13 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
14 SYSTEMPATH\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', [...])
15 SYSTEMPATH\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
16 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
17 SYSTEMPATH\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', [...])
18 SYSTEMPATH\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
19 SYSTEMPATH\CodeIgniter.php(655): CodeIgniter\Config\BaseService::__callStatic('createRequest', [...])
20 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
21 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2024-12-07 17:39:49 --> ErrorException: Uncaught CodeIgniter\Exceptions\ConfigException: Config\App::$baseURL "https//localhost/abcbmy/" is not a valid URL. in C:\xampp\htdocs\abcbmy\system\HTTP\SiteURI.php:199
Stack trace:
#0 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\abcbmy\system\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\abcbmy\system\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\abcbmy\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\abcbmy\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(NULL, false)
#13 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\abcbmy\system\Config\Services.php(520): CodeIgniter\Config\BaseService::getSharedInstance('request', NULL)
#15 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request()
#16 C:\xampp\htdocs\abcbmy\system\Debug\Exceptions.php(150): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#17 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Exceptions\ConfigException))
#18 {main}
  thrown
【Previous Exception】
CodeIgniter\Exceptions\ConfigException
Config\App::$baseURL "https//localhost/abcbmy/" is not a valid URL.
#0 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURI.php(145): CodeIgniter\HTTP\SiteURI->normalizeBaseURL(Object(Config\App))
#1 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURI.php(100): CodeIgniter\HTTP\SiteURI->determineBaseURL(Object(Config\App), NULL, NULL)
#2 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURIFactory.php(224): CodeIgniter\HTTP\SiteURI->__construct(Object(Config\App), '/', NULL)
#3 C:\xampp\htdocs\abcbmy\system\HTTP\SiteURIFactory.php(45): CodeIgniter\HTTP\SiteURIFactory->createURIFromRoutePath('/')
#4 C:\xampp\htdocs\abcbmy\system\Config\Services.php(799): CodeIgniter\HTTP\SiteURIFactory->createFromGlobals()
#5 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri(NULL, false)
#6 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#7 C:\xampp\htdocs\abcbmy\system\Config\Services.php(792): CodeIgniter\Config\BaseService::getSharedInstance('uri', NULL)
#8 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::uri()
#9 C:\xampp\htdocs\abcbmy\system\Config\Services.php(566): CodeIgniter\Config\BaseService::__callStatic('uri', Array)
#10 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App), false)
#11 C:\xampp\htdocs\abcbmy\system\Config\Services.php(524): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#12 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::request(Object(Config\App), false)
#13 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(199): CodeIgniter\Config\BaseService::__callStatic('request', Array)
#14 C:\xampp\htdocs\abcbmy\system\Config\Services.php(559): CodeIgniter\Config\BaseService::getSharedInstance('request', Object(Config\App))
#15 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::incomingrequest(Object(Config\App))
#16 C:\xampp\htdocs\abcbmy\system\Config\Services.php(539): CodeIgniter\Config\BaseService::__callStatic('incomingrequest', Array)
#17 C:\xampp\htdocs\abcbmy\system\Config\BaseService.php(258): CodeIgniter\Config\Services::createRequest(Object(Config\App))
#18 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(655): CodeIgniter\Config\BaseService::__callStatic('createRequest', Array)
#19 C:\xampp\htdocs\abcbmy\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->getRequestObject()
#20 C:\xampp\htdocs\abcbmy\index.php(79): CodeIgniter\CodeIgniter->run()
#21 {main}
in SYSTEMPATH\HTTP\SiteURI.php on line 199.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
